
# Load Libraries / Data

In [1]:
%run ../modules/library_to_import.ipynb

In [2]:
%run ../modules/Class_imdb.ipynb
%run ../modules/transformers_imdb.ipynb

In [3]:
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import seaborn as sns
# sns.despine()
sns.set()
# sns.set(style='white', context='notebook', palette='deep')
# sns.set(style='white', palette='deep')
sns.despine()

In [4]:
import warnings
from sklearn.exceptions import DataConversionWarning
warnings.filterwarnings(action='ignore', category=DataConversionWarning)
warnings.filterwarnings("ignore", category=DeprecationWarning) 
warnings.filterwarnings("ignore", category=FutureWarning)  
warnings.filterwarnings("ignore", category=UserWarning)  

np.set_printoptions(precision=2)

In [5]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

evaluations_all -  it is a dictionary where all the information regarding models performance scores gets recorded. It`s the 'cloud'.

By acessing the 'cloud' the Class Super_Analtica will work in groups.
Analytica_bolada is lower level.

## Data

In [6]:
df = pd.read_csv('../../data/movie_data.csv')
df.head(5)

                                              review  sentiment
0  It's hard to put your finger on this one. Basi...          1
1  I mean, nothing happens, 5 dumb kids go to Okl...          0
2  "Så som in himmelen" was probably one of the 3...          1
3  This noir may not be the best remembered film ...          1
4  I'll be honest with yall, I was a junior in hi...          1

In [7]:
X = df['review'].values
y = df['sentiment'].values

In [8]:
# %load ./params_imdb.ipynb

In [9]:
df.head()
df.info()

                                              review  sentiment
0  It's hard to put your finger on this one. Basi...          1
1  I mean, nothing happens, 5 dumb kids go to Okl...          0
2  "Så som in himmelen" was probably one of the 3...          1
3  This noir may not be the best remembered film ...          1
4  I'll be honest with yall, I was a junior in hi...          1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
review       50000 non-null object
sentiment    50000 non-null int64
dtypes: int64(1), object(1)
memory usage: 781.3+ KB

In [10]:
df.sentiment.value_counts(normalize=True)

1    0.5
0    0.5
Name: sentiment, dtype: float64

feature union is for applying different vectorizers for different columns

# X  y

In [11]:
random_state = 42

# # DATAFRAMES USED ONLY WHEN NEED MORE THAN 1 COLUMN
# WORKS with sklearn-pandas to drive dataframes in sklearn or column extractor e To_Matrix

# X_train = df.loc[:200, ['review']].reset_index(drop=True)
# y_train = df.loc[:200, ['sentiment']].reset_index(drop=True)
# X_test = df.loc[49900:, ['review']].reset_index(drop=True)
# y_test = df.loc[49900:, ['sentiment']].reset_index(drop=True)

# X_train = df.loc[:200, ['review']].reset_index(drop=True)
# y_train = df.loc[:200, ['sentiment']].reset_index(drop=True)
# X_test = df.loc[49800:, ['review']].reset_index(drop=True)
# y_test = df.loc[49800:, ['sentiment']].reset_index(drop=True)

# AQUIIIIIII
# X_train = df.loc[:8000, ['review']].reset_index(drop=True)
# y_train = df.loc[:8000, ['sentiment']].reset_index(drop=True)
# X_test = df.loc[46000:, ['review']].reset_index(drop=True)
# y_test = df.loc[46000:, ['sentiment']].reset_index(drop=True)

# X_train = df.loc[:10000, ['review']].reset_index(drop=True)
# y_train = df.loc[:10000, ['sentiment']].reset_index(drop=True)
# X_test = df.loc[40000:, ['review']].reset_index(drop=True)
# y_test = df.loc[40000:, ['sentiment']].reset_index(drop=True)

X_train = df.loc[:12000, ['review']].reset_index(drop=True)
y_train = df.loc[:12000, ['sentiment']].reset_index(drop=True)
X_test = df.loc[46000:, ['review']].reset_index(drop=True)
y_test = df.loc[46000:, ['sentiment']].reset_index(drop=True)

# X_train = df.loc[:20000, ['review']].reset_index(drop=True)
# y_train = df.loc[:20000, ['sentiment']].reset_index(drop=True)
# X_test = df.loc[45000:, ['review']].reset_index(drop=True)
# y_test = df.loc[45000:, ['sentiment']].reset_index(drop=True)


# kfold = StratifiedKFold(n_splits=10, shuffle=False, random_state=random_state)
kfold = StratifiedKFold(n_splits=8, shuffle=False, random_state=random_state)
# kfold = 5
# kfold = 4

In [12]:
X_train

                                                  review
0      It's hard to put your finger on this one. Basi...
1      I mean, nothing happens, 5 dumb kids go to Okl...
2      "Så som in himmelen" was probably one of the 3...
3      This noir may not be the best remembered film ...
4      I'll be honest with yall, I was a junior in hi...
5      Damon Runyon's world of Times Square, in New Y...
6      After a group of young friends experience car ...
7      What makes for Best Picture material? The Osca...
8      I found this film extremely disturbing. Treadw...
9      This DVD set is the complete widescreen 15-epi...
10     Kevin Kline and Meg Ryan are among that class ...
11     Well...there were some great, creamy-smooth fa...
12     If I had not read Pat Barker's 'Union Street' ...
13     This movie is fun to watch. If you liked "Dave...
14     A charming, funny film that gets a solid grade...
15     The movie is about a day in the life of a woma...
16     I just rented this movie from the video store ...
17     I suppose I always felt that Hotel du Nord was...
18     I saw this on cable. Someone had to lose their...
19     I was one of quite a few extras in this big bo...
20     Raising Victor Vargas is a movie you definitel...
21     First of all, I believe that this movie is muc...
22     Jörg Buttgereit goes a bit too far with his mo...
23     I had the opportunity to see this last evening...
24     Certainly not horrible, but definitely not goo...
25     Before watching this movie from beginning to e...
26     Outrageously trashy karate/horror thriller wit...
27     "Death Promise" is a lost 70's exploitation ge...
28     Of the Korean movies I've seen, only three had...
29     Of course I have disappeared into the movies. ...
...                                                  ...
11971  I tried restarting the movie twice. I put it i...
11972  They probably should have called this movie Th...
11973  This movie was way too slow and predictable.I ...
11974  This is a strong recommendation to anyone who ...
11975  Although flawed in it's view of homosexuals, t...
11976  This movie defines the word "confused". All th...
11977  It amazes me that anyone would find Pauly Shor...
11978  Might end up being the biggest disappointment ...
11979  I love Stephen Kings work and the book was gre...
11980  A series of random, seemingly insignificant th...
11981  ...I saw this movie when it first came out in ...
11982  Very rarely do I give less rave reviews on a s...
11983  I for one was very anxious to watch this movie...
11984  The fact that someone actually spent money on ...
11985  Ru Paul plays a secret agent called Starrbooty...
11986  Supposedly, a movie about a magazine sending j...
11987  It is written in stone that Disney animations ...
11988  I liked it better than House Party 2 & 3. The ...
11989  I saw this movie the other day in a film schoo...
11990  This juvenile, bland flick is strictly for tee...
11991  I viewed my videotape last night, for the firs...
11992  The Unseen is done in a style more like old Ho...
11993  Another tiresome bore from Anthony Minghella, ...
11994  OK, I don't want to upset anyone who enjoyed t...
11995  What this film has is its realism , you really...
11996  It's fun to watch a young James Cagney doing h...
11997  I am amazed at the amount of praise that is he...
11998  Eric Phillips (Don Wilson) is a secret service...
11999  'SherryBaby' is quite a painful and sordid mel...
12000  The movie 'Heart of Darkness', based on the 18...

[12001 rows x 1 columns]

In [13]:
X_test

                                                 review
0     Rich, alcoholic Robert Stack falls in love wit...
1     Don't understand how these animated movies kee...
2     Wings Hauser and son, Cole Hauser team up to m...
3     I always hated this retarded show .I liked the...
4     The movie never becomes intolerable to watch. ...
5     The SF premise isn't unique (although it prett...
6     Pink Flamingos is a movie no word can explain....
7     This program was quite interesting. The way th...
8     Sometimes a movie is so bad it's kind of good....
9     I saw Beyond Rangoon about 20 times, it was TH...
10    Get ready for it: This is one of my favourite ...
11    I thought this was a great idea but, boy, was ...
12    This is a hard show to watch. It's not somethi...
13    Had she not been married to the producer, Jenn...
14    Very strange but occasionally elegant exploita...
15    The sword fighting was out of this world, the ...
16    I thought this was a truly awful film--I found...
17    This movie was horrible, simply put. It was so...
18    I enjoy gay-themed movies where the characters...
19    I'm probably one of the few people who defend ...
20    Nay Sayers of this film are likely bitter from...
21    When I first saw "A Cry in the Dark", I had no...
22    I remember this film fondly from seeing it in ...
23    Ang Lee clearly likes to ease into a film, to ...
24    The movie opens with beautiful landscape shots...
25    Well, it wasn't a complete waste. Armand was a...
26    I've seen some very terrible horror movies in ...
27    **Might contain spoilers**<br /><br />Ok, lets...
28    While John Garfield seems to get the bulk of a...
29    Chris Penn is hilarious as the all-time stoner...
...                                                 ...
3970  I understand what this movie was trying to por...
3971  There is part of one sequence where some water...
3972  I think we all begin a lot of reviews with, "T...
3973  My daughter liked it but I was aghast, that a ...
3974  I just saw this film again, I believe for the ...
3975  It utterly defeats me why Godard is taken so s...
3976  Jimmy (Heath Ledger) is given a simple job by ...
3977  I attempted to watch this film without being a...
3978  Bloody Birthday plays on the assumed innocence...
3979  Disappointing film. Performance of actors is w...
3980  One of Warner Brothers best and highest grossi...
3981  How this has not become a cult film I do not k...
3982  The laughs are few and far between in this dul...
3983  I wouldn't call "We're Back! A Dinosaur's Stor...
3984  I contend that whoever is ultimately responsib...
3985  This was a well written tale of the Making of ...
3986  Even if you know absolutely nothing about Irel...
3987  `Rock star' is not on its way to any `stairway...
3988  I bought this game on an impulse buy from walm...
3989  A poorly-paced sf/horror venture that takes it...
3990  I don't understand how this garbage got on the...
3991  What seemed as a good premise for a movie...un...
3992  Although compared with "Mad Max", this film is...
3993  This show is a show that is great for adults a...
3994  (No spoilers, just plot details) I can't under...
3995  I'd heard this Japanese flick is edgy, creativ...
3996  The director does not know what to do with a c...
3997  I've seen this movie after watching Paltrow's ...
3998  I could never stand watching Happy Days after ...
3999  Stephen Hawkings is a genius. He is the king o...

[4000 rows x 1 columns]

In [14]:
y_train

       sentiment
0              1
1              0
2              1
3              1
4              1
5              1
6              1
7              1
8              0
9              1
10             0
11             0
12             0
13             1
14             1
15             0
16             1
17             1
18             0
19             0
20             1
21             1
22             1
23             1
24             0
25             1
26             0
27             1
28             1
29             0
...          ...
11971          0
11972          0
11973          0
11974          0
11975          1
11976          0
11977          0
11978          0
11979          0
11980          1
11981          1
11982          0
11983          1
11984          0
11985          0
11986          0
11987          1
11988          1
11989          0
11990          0
11991          1
11992          1
11993          0
11994          0
11995          0
11996          1
11997          0
11998          0
11999          0
12000          0

[12001 rows x 1 columns]

In [15]:
y_test

      sentiment
0             1
1             0
2             0
3             0
4             0
5             1
6             1
7             1
8             1
9             1
10            1
11            0
12            1
13            0
14            0
15            1
16            0
17            0
18            0
19            0
20            1
21            1
22            1
23            1
24            0
25            0
26            0
27            0
28            1
29            1
...         ...
3970          0
3971          0
3972          0
3973          0
3974          1
3975          0
3976          1
3977          0
3978          1
3979          0
3980          1
3981          1
3982          0
3983          1
3984          1
3985          1
3986          1
3987          1
3988          1
3989          0
3990          0
3991          0
3992          1
3993          1
3994          1
3995          0
3996          0
3997          1
3998          0
3999          1

[4000 rows x 1 columns]

In [16]:
X_train.shape
# X_train.info()
type(X_train)

(12001, 1)

pandas.core.frame.DataFrame

In [17]:
y_train.shape
# y_train.info()
type(y_train)

(12001, 1)

pandas.core.frame.DataFrame

In [18]:
X_test.shape
# X_test.info()
type(X_test)

(4000, 1)

pandas.core.frame.DataFrame

In [19]:
y_test.shape
# y_train.info()
type(y_test)

(4000, 1)

pandas.core.frame.DataFrame

# PRE LOADING

In [20]:
def tokenizer_split(text):
    return [porter.stem(w) for w in text.split(' ')]

def tokenizer_porter(text):
    return [porter.stem(w) for w in text.split(' ') if not w in stop_words ]

tfidf = TfidfVectorizer(strip_accents=None, lowercase=False, preprocessor=None)

In [21]:
master = Super_Analytica('master')

In [22]:
stop_words = nltk.corpus.stopwords.words('english')
porter = PorterStemmer()

In [23]:
%run ../modules/params_imdb.ipynb

# Vocabulary

In [26]:
%%time
# Defining Vocab
pipe = Pipeline([
    ('col', Col_Extractor(['review'])),
    ('prep', Preprocessor()),
    ('to_array', To_array()),
    ('counts', CountVectorizer(max_features=5000, stop_words='english', min_df=3, 
                               tokenizer=tokenizer_porter))
])

train_features_matrix_1 = pipe.fit_transform(X_train)
vocab = pipe.named_steps['counts'].get_feature_names()

CPU times: user 59 s, sys: 502 ms, total: 59.5 s
Wall time: 1min

In [24]:
filename = 'vocab_5'

In [25]:
# saving vocabulary with pickle
# joblib.dump(vocab, '../pkl/'+ filename + '.pkl') 

# loading vocabulary previoulsy pickled
vocab = joblib.load('../pkl/'+ filename + '.pkl') 
len(vocab)

5000

# Load Pickle

In [26]:
# for i in md_7_all:
#     master.pkl_R(i)

# Selecting Pipeline

fazer um comparativo entre pipelines onde o vextorizer é o TFIDF e onde o vectorizer esta 
dividido entre CountVect + TFIDF. Desse comparativo sai o pipeline que sera usado para o HP

In [27]:
nc = 5000

## Mostrar como Truncated demora muito mais. Rodar em SGCD. teste simples

In [40]:
# Conslusao é retirar Truncated dos pipelines posteriores. Podemos criar dois fature_matrix  
# com a mesma qnt de features e mostrar como mesmo assim cada processo demora tempos bem diferentes.
# Qual percentile gera a mesma quantidade de features de n_components ?

pipe_1 = Pipeline([
    ('col', Col_Extractor(['review'])),
    ('prep', Preprocessor()),
    ('to_array', To_array()),
    ('tf-idf_vec', TfidfVectorizer()),
    ('TruncatedSVD', TruncatedSVD(n_components=nc))
])

# variacao do pipe 1
pipe_2 = Pipeline([
    ('col', Col_Extractor(['review'])),
    ('prep', Preprocessor()),
    ('to_array', To_array()),
    ('vec', TfidfVectorizer()),  
    ('kbest', SelectPercentile(chi2))

])

master.evaluate_CV(pipe_1, ['LGR']) # precisa de pickle mesmo ?
master.evaluate_CV(pipe_2, ['LGR']) 


# Demorou quase duas horas sem nenhum resultado. Talvez usar LGR ao inves de SGDC

LGR   Cross Validation Done in  140.0  minutes  /-->acc : 0.9461256613598805

LGR   Cross Validation Done in  1.0  minutes  /-->acc : 0.9418144357206958

- Os pipes 2 e 3 tem reducao de dimensionalidade para algoritmos Non-Parametric
- clf_T = ['DT', 'ADA', 'RF', 'XT'] + ['KNN']

In [29]:
pipe_2 = Pipeline([
    ('col', Col_Extractor(['review'])),
    ('prep', Preprocessor()),
    ('to_array', To_array()),
    ('vec', TfidfVectorizer()),  
    ('kbest', SelectPercentile(chi2))

])

pipe_3 = Pipeline([
    ('col', Col_Extractor(['review'])),
    ('prep', Preprocessor()),
    ('to_array', To_array()),
    ('counts', CountVectorizer()),
    ('tf-idf', TfidfTransformer()),
    ('kbest', SelectPercentile(chi2))
])

NonP_algos = clf_T + ['KNN']

In [30]:
master.evaluate_CV(pipe_2, NonP_algos, '_pp2', pkl_W=True)
master.evaluate_CV(pipe_3, NonP_algos, '_pp3', pkl_W=True)

DT_pp2   Cross Validation and Pickled Done in  2.0  minutes  /-->acc : 0.7004344978984807

ADA_pp2   Cross Validation and Pickled Done in  2.0  minutes  /-->acc : 0.7004691647179794

RF_pp2   Cross Validation and Pickled Done in  1.0  minutes  /-->acc : 0.8393749548291103

XT_pp2   Cross Validation and Pickled Done in  1.0  minutes  /-->acc : 0.8588309908290338

KNN_pp2   Cross Validation and Pickled Done in  2.0  minutes  /-->acc : 0.6506266025019131

DT_pp3   Cross Validation and Pickled Done in  2.0  minutes  /-->acc : 0.7004344978984807

ADA_pp3   Cross Validation and Pickled Done in  2.0  minutes  /-->acc : 0.7004691647179794

RF_pp3   Cross Validation and Pickled Done in  1.0  minutes  /-->acc : 0.8393749548291103

XT_pp3   Cross Validation and Pickled Done in  1.0  minutes  /-->acc : 0.8588309908290338

KNN_pp3   Cross Validation and Pickled Done in  1.0  minutes  /-->acc : 0.6506266025019131

- Os pipes 3 e 4 nao tem reducao de dimensionalidade, para algo parametricos
- clf_L = ['LinearSVC', 'LGR', 'RDG'] + ['NB', 'SGDC']

In [31]:
pipe_4 = Pipeline([
    ('col', Col_Extractor(['review'])),
    ('prep', Preprocessor()),
    ('to_array', To_array()),
    ('tf-idf_vec', TfidfVectorizer())
])


pipe_5 = Pipeline([
    ('col', Col_Extractor(['review'])),
    ('prep', Preprocessor()),
    ('to_array', To_array()),
    ('counts', CountVectorizer()),
    ('tf-idf', TfidfTransformer())
])

P_algos = clf_L + ['NB', 'SGDC']

In [32]:
master.evaluate_CV(pipe_4, P_algos, '_pp4', pkl_W=True)
master.evaluate_CV(pipe_5, P_algos, '_pp5', pkl_W=True)

LinearSVC_pp4   Cross Validation and Pickled Done in  1.0  minutes  /-->acc : 0.9500987960977996

LGR_pp4   Cross Validation and Pickled Done in  1.0  minutes  /-->acc : 0.9467280360504089

RDG_pp4   Cross Validation and Pickled Done in  1.0  minutes  /-->acc : 0.9501826730892771

NB_pp4   Cross Validation and Pickled Done in  1.0  minutes  /-->acc : 0.9343157510922356

SGDC_pp4   Cross Validation and Pickled Done in  1.0  minutes  /-->acc : 0.950817475474315

LinearSVC_pp5   Cross Validation and Pickled Done in  1.0  minutes  /-->acc : 0.9500987960977996

LGR_pp5   Cross Validation and Pickled Done in  1.0  minutes  /-->acc : 0.9467280360504089

RDG_pp5   Cross Validation and Pickled Done in  1.0  minutes  /-->acc : 0.9501868938722784

NB_pp5   Cross Validation and Pickled Done in  1.0  minutes  /-->acc : 0.9343157510922356

SGDC_pp5   Cross Validation and Pickled Done in  1.0  minutes  /-->acc : 0.950817475474315

# PLOTTING

In [33]:
master.get_members_evaluations_all()

dict_keys(['DT_pp2', 'ADA_pp2', 'RF_pp2', 'XT_pp2', 'KNN_pp2', 'DT_pp3', 'ADA_pp3', 'RF_pp3', 'XT_pp3', 'KNN_pp3', 'LinearSVC_pp4', 'LGR_pp4', 'RDG_pp4', 'NB_pp4', 'SGDC_pp4', 'LinearSVC_pp5', 'LGR_pp5', 'RDG_pp5', 'NB_pp5', 'SGDC_pp5'])

In [34]:
%%time
master.plot_learning_curve(load_saved=False)

saving l_curve_ image for  DT_pp2
saving l_curve_ image for  ADA_pp2
saving l_curve_ image for  RF_pp2
saving l_curve_ image for  XT_pp2
saving l_curve_ image for  KNN_pp2
saving l_curve_ image for  DT_pp3
saving l_curve_ image for  ADA_pp3
saving l_curve_ image for  RF_pp3
saving l_curve_ image for  XT_pp3
saving l_curve_ image for  KNN_pp3
saving l_curve_ image for  LinearSVC_pp4
saving l_curve_ image for  LGR_pp4
saving l_curve_ image for  RDG_pp4
saving l_curve_ image for  NB_pp4
saving l_curve_ image for  SGDC_pp4
saving l_curve_ image for  LinearSVC_pp5
saving l_curve_ image for  LGR_pp5
saving l_curve_ image for  RDG_pp5
saving l_curve_ image for  NB_pp5
saving l_curve_ image for  SGDC_pp5
CPU times: user 51min 28s, sys: 10min 26s, total: 1h 1min 55s
Wall time: 1h 3min 25s

In [35]:
%%time
master.plot_Classification_Report( load_saved=False)

saving c_reprt_ image for DT_pp2
saving c_reprt_ image for ADA_pp2
saving c_reprt_ image for RF_pp2
saving c_reprt_ image for XT_pp2
saving c_reprt_ image for KNN_pp2
saving c_reprt_ image for DT_pp3
saving c_reprt_ image for ADA_pp3
saving c_reprt_ image for RF_pp3
saving c_reprt_ image for XT_pp3
saving c_reprt_ image for KNN_pp3
saving c_reprt_ image for LinearSVC_pp4
saving c_reprt_ image for LGR_pp4
saving c_reprt_ image for RDG_pp4
saving c_reprt_ image for NB_pp4
saving c_reprt_ image for SGDC_pp4
saving c_reprt_ image for LinearSVC_pp5
saving c_reprt_ image for LGR_pp5
saving c_reprt_ image for RDG_pp5
saving c_reprt_ image for NB_pp5
saving c_reprt_ image for SGDC_pp5
CPU times: user 2min 30s, sys: 33.1 s, total: 3min 3s
Wall time: 3min 8s

In [36]:
%%time
master.plot_Confusion_Matrix( load_saved=False)

saving c_matrx_ image for DT_pp2
saving c_matrx_ image for ADA_pp2
saving c_matrx_ image for RF_pp2
saving c_matrx_ image for XT_pp2
saving c_matrx_ image for KNN_pp2
saving c_matrx_ image for DT_pp3
saving c_matrx_ image for ADA_pp3
saving c_matrx_ image for RF_pp3
saving c_matrx_ image for XT_pp3
saving c_matrx_ image for KNN_pp3
saving c_matrx_ image for LinearSVC_pp4
saving c_matrx_ image for LGR_pp4
saving c_matrx_ image for RDG_pp4
saving c_matrx_ image for NB_pp4
saving c_matrx_ image for SGDC_pp4
saving c_matrx_ image for LinearSVC_pp5
saving c_matrx_ image for LGR_pp5
saving c_matrx_ image for RDG_pp5
saving c_matrx_ image for NB_pp5
saving c_matrx_ image for SGDC_pp5
CPU times: user 2min 29s, sys: 31.8 s, total: 3min 1s
Wall time: 3min 4s

In [37]:
master.get_members_evaluations_all()

dict_keys(['DT_pp2', 'ADA_pp2', 'RF_pp2', 'XT_pp2', 'KNN_pp2', 'DT_pp3', 'ADA_pp3', 'RF_pp3', 'XT_pp3', 'KNN_pp3', 'LinearSVC_pp4', 'LGR_pp4', 'RDG_pp4', 'NB_pp4', 'SGDC_pp4', 'LinearSVC_pp5', 'LGR_pp5', 'RDG_pp5', 'NB_pp5', 'SGDC_pp5'])

In [38]:
print('Done')

Done